### PR TITLE
Fix travis-ci script

### PR DESCRIPTION
**Pull request by Crayon2000**
This will fix the problem with Travis CI.

Instead of downloading the DevkitPro perl script for installation, I am now explicitly choosing the proper version to use. The filename / version are in the ini file: http://devkitpro.sourceforge.net/devkitProUpdate.ini

There is a bit more lines, but there is no need to use extra perl and ini files.

### CODE REVIEW

**Comment by Crayon2000** [comment]
@Maschell, I posted this solution 22 hours ago, is there a reason why this wasn't used. This solution look better than the one added 8 hours ago?

**Comment by Maschell** [comment]
I simply didn't see the PR, sorry.
I'll take a look at your solution tomorrow, thanks!

**Comment by Maschell** [comment]
I just saw you added libogc/libfat.
Libutils doesn't require them, so they could be removed, right? Or is there any other reason for including them?

**Comment by Crayon2000** [comment]
@Maschell I just did a commit to remove libfat. It was not required. The PR was updated so it can be merged back to master.

**Pull request merged**
